const mongoose = require('mongoose');

const pdtSchema = new mongoose.Schema({
    customer_no: String,
    buying_group: String,
    cust_grp1: String,
    customer_group_3: String,
    name_2: String,
    customer_name: String,
    address_1: String,
    address_2: String,
    city: String,
    pincode: String,
    contact_person: String,
    telephone_no: String,
    mobile_phone: String,
    sales_group: String,
    customer_group: String,
    county_code: String,
    email_id1: String,
    email_id2: String,
    email_id3: String,
    email_id4: String,
    vat_registration_no: String,
    pan_no: String,
    date_of_appointment: String,
    city_code: String,
    sales_district: String,
    cust_grp2: String,
    customer_group_5: String,
    sort: String,
    region_description: String,
    district: String,
    deactivate_date: String,
    reactivate_date: String,
    tax_no3: String,
    distribution_channel: String,
    region: String,
    central_order_block: String,
    central_delivery_block: String,
    sales_area_deletion: String,
    division: String,
    spouse_name: String,
    mariiage_date: String,
    date_of_birth: String,
    gender: String,
    marital_status: String,
    trading_partner: String,
    draft_limit: String,
    credit_limit: String,
    credit_exposure: String,
    sales_org: String,
    sales_office: String,
    central_deletion_flag: String,
    central_billing_block: String,
    sa_order_block: String,
    sa_deliver_block: String,
    sa_billing_block: String,
    customer_group_4: String,
    unloading_point: String,
    credit_ac_no: String,
    thane_transporter: String,
    chindwara_transporter: String,
    vapi_transporter: String,
    thane_courier: String,
    chindwara_courier: String,
    vapi_courier: String,
    jalgaon_transporter: String,
    created_on: String,
    home_city: String,
    created_by: String,
    customer_classification: String,
    cust_pric_proce: String,
    recon_acct: String,
    ws_custno: String,
    ws_name: String,
    ws_city: String,
    price_group: String,
    customer_tax_classification: String,
    customer_key: String,
    data_processed: Boolean
}, {
    timestamps: true,
    toObject: {
        transform: function (doc, ret, options) {
            ret.id = ret._id;
            delete ret._id;
            delete ret.__v;
            return ret;
        }
    }
});

module.exports = mongoose.model('zsd_customer_details', pdtSchema, 'zsd_customer_details');